apiVersion: v1
kind: Secret
metadata:
  name: consoleweb
type: Opaque
stringData:
  user: <WEBUI-USERNAME>
  password: <WEBUI-PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: console
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/rpsdb?sslmode=<SSL-MODE>
  encryptionKey: <APP-ENCRYPTION-KEY>
  jwtKey: <JWT-SECRET-KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: mpsrouter
type: Opaque
stringData:
  connectionString: postgresql://<DATABASE-USERNAME>:<DATABASE-PASSWORD>@<DATABASE-SERVER-URL>:5432/mpsdb?sslmode=<SSL-MODE>
---
apiVersion: v1
kind: Secret
metadata:
  name: device-mgmt-toolkit-admin-jwt
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  kongCredType: jwt
  key: admin-issuer
  algorithm: HS256
  secret: <YOUR-SECRET>
---
apiVersion: v1
kind: Secret
metadata:
  name: device-mgmt-toolkit-admin-acl
  labels:
    konghq.com/credential: acl
type: Opaque
stringData:
  kongCredType: acl
  group: device-mgmt-toolkit-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
type: Opaque
stringData:
  vaultKey: <VAULT-ROOT-TOKEN>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  password: <POSTGRES-PASSWORD>
---
